In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
df = pd.io.parsers.read_csv(
    'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',
    )
df.columns=['a','b','c','d','label']
df.head()

a    b    c    d        label
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [5]:
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(df.values[:,0:4], df.values[:,4])
print(model)
# make predictions
expected = df.values[:,4]
predicted = model.predict(df.values[:,0:4])
# summarize the fit of the model
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_neighbors=5, p=2, weights='uniform')
             precision    recall  f1-score   support

Iris-setosa       1.00      1.00      1.00        49
Iris-versicolor       0.96      0.94      0.95        50
Iris-virginica       0.94      0.96      0.95        50

avg / total       0.97      0.97      0.97       149

[[49  0  0]
 [ 0 47  3]
 [ 0  2 48]]


In [6]:
accuracy = metrics.accuracy_score(expected,predicted)*100
print '正確率=' + str(accuracy) + '%'

正確率=96.644295302%
